### ISSUE TITLE
Error creating new record

### ISSUE THREAD

**Issue by brendanheywood** [brendanheywood/moodle-mod_cpdlogbook#19]
Error writing to database

More information about this error

×Debug info: ERROR: syntax error at or near "user"
LINE 1: ...SERT INTO mdl_cpdlogbook_entries (name,cpdlogbook,user,time)...
^
INSERT INTO mdl_cpdlogbook_entries (name,cpdlogbook,user,time) VALUES($1,$2,$3,$4) RETURNING id
[array (
'name' => 'test',
'cpdlogbook' => '1',
'user' => '2',
'time' => 1629331187,
)]
Error code: dmlwriteexception
×Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 329 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 1134 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1182 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->insert_record_raw()
line 47 of /mod/cpdlogbook/edit.php: call to pgsql_native_moodle_database->insert_record()

**Comment by UndeclaredVariable** [comment]
This doesn't seem to happen for me with a MariaDB database.
I've made a small change that might fix the issue. Instead of the optional_param default being null, it's been changed to 0. Since the auto_increment field in the database starts at 1, this shouldn't cause any id collisions.
I've also unset the id from the form data when it's submitted. This should hopefully avoid any issues caused by the id field already existing on the object being inserted.

**Comment by brendanheywood** [comment]
Ah I see the issue, its with 'user'. This works in mysql / maria but does not in postgres. There is a complete list of reserved words here which spans all the databases:

https://docs.moodle.org/dev/XMLDB_reserved_words

There is a semi de facto standard that if you are linking to another table suffix the field with id, eg 'userid'
